language: java
jdk:
- openjdk7
- oraclejdk7
before_install:
- echo "JAVA6_HOME=$(jdk_switcher home jdk6)" >> gradle.properties
- cat gradle.properties
- export JAVA7_HOME=$(jdk_switcher home jdk7)
after_success:
- gradle travisRelease
env:
  secure: Sx+UTEqxv5ZuvM/A5TunfLttbUHdzFp5kzS79TetNXqwmurTQS+d80dASTuE2rgzNfsFAokCRU9ghx/WBjXiZ1vxtD5paQExM111L5fQk42ydv699gUN+FD+V4z8WBgcyuc1RDLHvHO1itw3q5LxvOjxgtbm76VDRkRNDSqpFpM=
